# This option is here to quickly toggle this expansion on a live server that must stay online.
# We recommend that you remove the Action Bar expansion jar if you will not use the feature.
enabled: true

# Scale is the amount of symbols for the {bars} placeholder.
scale: 15

# Left Color is the color code for the left part of the {bars} placeholder.
# A color MiniMessage tag value is required.
# Example 01: "<green></green>"
# Example 02: "<#00FF00></#00FF00>"
# Default: "<green></green>"
left-color-start: "<green>"
left-color-end: "</green>"

# Left Symbol is the symbol used for the left part of the {bars} placeholder
# Unicode is supported, but must be converted.
# Example: "/u00A7"
# Default: "|"
left-symbol: "|"

# Right Color is the color code for the right part of the {bars} placeholder.
# A color MiniMessage tag value is required.
# Example 01: "<red></red>"
# Example 02: "<#FF0000></#FF0000>"
# Default: "<red></red>"
right-color-start: "<red>"
right-color-end: "</red>"

# Right Symbol is the symbol used for the right part of the {bars} placeholder
# Unicode is supported, but must be converted.
# Example: "/u00A7"
# Default: "|"
right-symbol: "|"
