# Should players in vanish be preventing from going into combat?
prevent-vanish-tagging-self: true

# Should players in vanish be unable to tag other players?
prevent-vanish-tagging-other: true

# Should teleport requests be disabled during combat?
prevent-teleport-request: true
