# Config Options for CombatLogX
options:
  # Set this to true if you want to check for updates
  # This will not automatically download them
  # Default: true
  check for updates: true
  
  # Add worlds to this list if you do not want players to be tagged in them
  disabled worlds:
  - "world1"
  - "world2"
  
  broadcasts:
    # Set this to true if you want to broadcast a message when the plugin is enabled.
    # Default: true
    on enable: true
    
    # Set this to true if you want to broadcast a message when the plugin is disabled.
    # Default: true
    on disable: true
    
  # The amount of time (in seconds) that players will be tagged before they can log out.
  # If they leave before this time ends, they will be punished.
  # Default: 30
  time: 30
  
  link:
    # Set this to true to link arrows, potions, snowballs, eggs, and other projectiles to the entity that shot them
    # This will only link the shooter if they are the attacker
    # Default: true
    projectiles: true
    
    # Set this to true to link wolves, ocelots, parrots, and other pets to the entity that owns them
    # This will only link the owner if their pet is the attacker
    # Default: true
    pets: true

# Punishment options for CombatLogX
punish:
  # Set this to true if players should be punished when they log out during combat
  # Default: true
  on quit: true
  
  # Set this to true if players should be punished when they get kicked by a plugin or staff member during combat
  # Default: false
  on kick: false
  
  # Set this to true if players should be punished when their combat timer expires
  # You should never need this option but its here for debugging purposes
  # Default: false 
  on expire: false
  
  # Set this to true if players should be killed when they are punished
  # Default: true
  kill: true
  
  sudo:
    # Set this to true if players/console should run commands when a player is punished
    # Default: false
    enabled: false
    
    # List of commands if the above option is set to true
    # Prefix with [CONSOLE] to run as console 
    # Prefix with [PLAYER] to run as the player
    # Prefix with [OP] to run as the player but with "Server Operator" permissions
    commands:
    - "[CONSOLE]eco take {player} 100"
    - "[PLAYER]me logged out during combat!"
 
# Combat options for CombatLogX   
combat:
  # Set this to true if players should be untagged when their current enemy dies
  # Default: false
  untag on enemy death: false
  
  # Set this to true if players should be untagged when they die
  # Default: true
  untag on self death: true
  
  bypass:
    # Set this to true if players should be allowed to bypass combat. You will need to give them the permission that is configured below
    # Default: false
    allow: false
    
    # Change this if you don't like the default permission
    permission: "combatlogx.bypass"
  
  # Set this to true to allow players to tag themselves
  # Default: true
  self: true
  
  mobs:
    # Set this to true to allow mobs to tag players
    # Default: true
    enabled: true
    
    # List of mobs that do not cause combat
    blacklist:
    - WITHER
    - ARMOR_STAND
  
  sudo:
    # Set this to true if players/console should run commands when a player is tagged
    # Default: false
    enabled: false
    
    # List of commands if the above option is set to true
    # Prefix with [CONSOLE] to run as console 
    # Prefix with [PLAYER] to run as the player
    # Prefix with [OP] to run as the player but with "Server Operator" permissions
    commands:
    - "[PLAYER]me is now in Combat"
    